#include "deployment.hpp"
#include "../service.hpp"
#include <crails/cli/process.hpp>
#include <crails/read_file.hpp>
#include <fstream>
#include <iostream>
#include <sstream>

using namespace std;
using namespace WebApp;

static string shell_quote(const string& value)
{
  static const string safe =
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_./:=@,+";
  string result("'");

  if (!value.empty() && value.find_first_not_of(safe) == string::npos)
    return value;
  for (char c : value)
  {
    if (c == '\'')
      result += "'\\''";
    else
      result += c;
  }
  return result + '\'';
}

bool Deployment::dropin_supported()
{
#ifdef __FreeBSD__
  return false;
#else
  return true;
#endif
}

filesystem::path Deployment::unit_path() const
{
  SystemService service;

  service.app_name = name;
  return service.service_file_path();
}

filesystem::path Deployment::dropin_directory() const
{
  return filesystem::path("/etc/systemd/system") / (name + ".service.d");
}

filesystem::path Deployment::dropin_path() const
{
  return dropin_directory() / "10-hostie.conf";
}

filesystem::path Deployment::release_environment_path() const
{
  return filesystem::path("/usr/share/crails-deploy") / name;
}

bool Deployment::install_dropin(const filesystem::path& hostie_environment) const
{
  error_code error;

  filesystem::create_directories(dropin_directory(), error);
  if (error)
  {
    cerr << "could not create " << dropin_directory() << ": " << error.message() << endl;
    return false;
  }
  ofstream stream(dropin_path());
  if (!stream.is_open())
  {
    cerr << "could not create " << dropin_path() << endl;
    return false;
  }
  // The main unit's EnvironmentFile entries come first, and drop-ins are
  // appended: a plain entry here would make hostie win over crails-deploy.
  // Resetting the list lets us state the order: later files override earlier.
  stream
    << "# Generated by hostie-cli. The unit file belongs to crails-deploy.\n"
    << "# Environment files, lowest to highest precedence: hostie, then the release.\n"
    << "[Service]\n"
    << "EnvironmentFile=\n"
    << "EnvironmentFile=" << hostie_environment.string() << '\n'
    << "EnvironmentFile=-" << release_environment_path().string() << '\n';
  stream.close();
  SystemService().reload_service_files();
  return true;
}

void Deployment::remove_dropin() const
{
  error_code error;

  filesystem::remove_all(dropin_directory(), error);
}

void Deployment::remove_artifacts() const
{
  error_code error;

#ifndef __FreeBSD__
  if (filesystem::exists(unit_path(), error))
  {
    Crails::run_command("systemctl disable " + name + ".service");
    filesystem::remove(unit_path(), error);
  }
  remove_dropin();
#endif
  filesystem::remove(release_environment_path(), error);
  SystemService().reload_service_files();
}

vector<string> WebApp::deploy_arguments(const InstanceEnvironment& environment)
{
  const string name = environment.get_project_name();
  const string user = environment.get_variable("APPLICATION_USER");
  const string group = environment.get_variable("APPLICATION_GROUP");
  // crails-deploy defaults: the user is the app name, the group is the user
  const string effective_user = user.empty() ? name : user;
  vector<string> arguments{
    "--app-name",     name,
    "--app-host",     environment.get_variable("APPLICATION_HOST"),
    "--app-port",     environment.get_variable("APPLICATION_PORT"),
    "--runtime-path", environment.get_variable("VAR_DIRECTORY")
  };

  if (effective_user != name)
  {
    arguments.push_back("--user");
    arguments.push_back(effective_user);
  }
  if (!group.empty() && group != effective_user)
  {
    arguments.push_back("--group");
    arguments.push_back(group);
  }
  return arguments;
}

string WebApp::deploy_arguments_line(const InstanceEnvironment& environment)
{
  ostringstream stream;
  bool first = true;

  for (const string& argument : deploy_arguments(environment))
  {
    if (!first) stream << ' ';
    stream << shell_quote(argument);
    first = false;
  }
  return stream.str();
}

string WebApp::deploy_example(const InstanceEnvironment& environment)
{
  const string name = environment.get_project_name();
  const vector<string> arguments = deploy_arguments(environment);
  vector<string> lines{
    "crails-deploy",
    "--package ./" + shell_quote(name) + ".tar.gz",
    "--hostname <server>",
    "--deploy-user root",
  };
  ostringstream stream;

  for (size_t i = 0 ; i + 1 < arguments.size() ; i += 2)
    lines.push_back(arguments[i] + ' ' + shell_quote(arguments[i + 1]));
  lines.push_back("--start " + shell_quote("/usr/local/bin/" + name));
  for (size_t i = 0 ; i < lines.size() ; ++i)
  {
    if (i > 0) stream << "  ";
    stream << lines[i];
    if (i + 1 < lines.size()) stream << " \\\n";
  }
  return stream.str();
}

void WebApp::warn_about_overrides(const InstanceEnvironment& hostie, ostream& out)
{
  static const struct { const char* key; bool secret; } pinned[] = {
    {"APPLICATION_HOST", false},
    {"APPLICATION_PORT", false},
    {"VAR_DIRECTORY",    false},
    {"DATABASE_URL",     true}
  };
  Deployment deployment(hostie.get_project_name());
  InstanceEnvironment release;
  string contents;

  if (!Crails::read_file(deployment.release_environment_path().string(), contents))
    return ; // not deployed yet
  release.append(string_view(contents));
  for (const auto& variable : pinned)
  {
    const string deployed = release.get_variable(variable.key);
    const string managed = hostie.get_variable(variable.key);

    if (!deployed.empty() && deployed != managed)
    {
      out << "warning: crails-deploy overrides " << variable.key;
      if (!variable.secret)
        out << " (hostie: " << managed << ", deployed: " << deployed << ')';
      out << ". hostie-cli keeps acting on its own value;"
          << " see `hostie-cli webapp deploy-args`." << endl;
    }
  }
}
