libs =
import libs += libcrails-cli%lib{crails-cli}
import libs += libcrails-random%lib{crails-random}
import libs += libcrails-readfile%lib{crails-readfile}
import libs += libcrails-database-url%lib{crails-database-url}
import libs += libcrails-encrypt%lib{crails-encrypt}
import libs += libboost-program-options%lib{boost_program_options}
import libs += libcrypto%lib{crypto}

exe{hostie-cli}: {hxx ixx txx cxx}{**} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root"
